### ISSUE TITLE
clash with arXiv title fixer extension

### ISSUE THREAD

**Issue by PBarde** [vict0rsch/ArxivTools#2]
Hey, 
Features 2 and 4 do not work when https://chrome.google.com/webstore/detail/arxiv-title-fixer/pandhendpghoedojdhookbedinmhjien?hl=en extension is enabled.

**Comment by vict0rsch** [comment]
@PBarde ok I'll investigate, I did not know about this one

**Comment by vict0rsch** [comment]
@PBarde would an option **not to** modify titles work for you?

**Comment by PBarde** [comment]
I am not sure I understand the "option not to modify title".

I think it would be nice to have both extensions work side by side so that the four features of ArxivTools work alongside arxiv-title-fixer that gives you nice tab titles.

If this is not possible, then maybe ArxivTools could incorporate arxiv-title-fixer's feature of displaying nice tabs titles so that people do not need to use arxiv-title-fixer alongside ArxivTools

**Comment by vict0rsch** [comment]
@PBarde Sorry I misunderstood ; I'll fix the compatibility **and** add this option within ArxivTools so that you don't need to have two extensions

**Comment by vict0rsch** [comment]
This should be fixed in v0.0.2 :) re-open if not
