### ISSUE TITLE
Adding "copy markdown entry"

### ISSUE THREAD

**Issue by armancohan** [vict0rsch/ArxivTools#7]
Thanks for the great extension! 
Would it be possible to add a "copy markdown entry" in addition to a "copy bibtex entry" when clicking on arxivtools button?
Currently there is a extra click + redirect to be able to copy the markdown entry.

**Comment by vict0rsch** [comment]
Hey @armancohan I just realeased a bran new version that actually stores papers and adds that functionality you asked for, check out https://github.com/vict0rsch/ArxivTools#guides
